{
 "title": "GOTN",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "embedding_similarity_check",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"gotn-metrics\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r._measurement == \"embedding_similarity_check\")\n  |> filter(fn: (r) => r._field == \"duration\")"
    }
   ]
  },
  {
   "title": "cpu_percent",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"gotn-metrics\")\n  |> range(start: -15m)\n  |> filter(fn: (r) => r._measurement == \"server_metrics\")\n  |> filter(fn: (r) => r._field == \"cpu_percent\")\n  |> yield(name: \"cpu_utilization\") "
    }
   ]
  },
  {
   "title": "streamlit_latency_ms",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"gotn-metrics\")\n  |> range(start: -15m)\n  |> filter(fn: (r) => r._measurement == \"server_metrics\")\n  |> filter(fn: (r) => r._field == \"streamlit_latency_ms\")\n  |> yield(name: \"streamlit_latency\")\n"
    }
   ]
  },
  {
   "title": "llm_structured_response",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "targets": [
    {
     "query": "from(bucket: \"gotn-metrics\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r._measurement == \"llm_structured_response\")\n  |> filter(fn: (r) => r._field == \"duration\")"
    }
   ]
  },
  {
   "title": "GPU Percent",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "targets": [
    {
     "query": "from(bucket: \"gotn-metrics\")\n  |> range(start: -15m)\n  |> filter(fn: (r) => r._measurement == \"server_metrics\")\n  |> filter(fn: (r) => r._field == \"gpu_percent\")\n  |> yield(name: \"gpu_utilization\") "
    }
   ]
  },
  {
   "title": "disk_percent",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "targets": [
    {
     "query": "from(bucket: \"gotn-metrics\")\n  |> range(start: -15m)\n  |> filter(fn: (r) => r._measurement == \"server_metrics\")\n  |> filter(fn: (r) => r._field == \"disk_percent\")\n  |> yield(name: \"disk_utilization\")\n"
    }
   ]
  },
  {
   "title": "llm_untructured_response",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "targets": [
    {
     "query": "from(bucket: \"gotn-metrics\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r._measurement == \"llm_unstructured_response\")\n  |> filter(fn: (r) => r._field == \"duration\")"
    }
   ]
  },
  {
   "title": "memory_percent",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "targets": [
    {
     "query": "from(bucket: \"gotn-metrics\")\n  |> range(start: -15m)\n  |> filter(fn: (r) => r._measurement == \"server_metrics\")\n  |> filter(fn: (r) => r._field == \"memory_percent\")\n  |> yield(name: \"memory_utilization\")"
    }
   ]
  }
 ]
}